CREATE TABLE `intervention_impact_analysis` (
	`id` int AUTO_INCREMENT NOT NULL,
	`intervention_type` enum('training','policy_change','organizational_change','corrective_action','awareness_campaign','other') NOT NULL,
	`intervention_name` varchar(255) NOT NULL,
	`description` text,
	`implementation_date` date NOT NULL,
	`target_department_id` int,
	`target_area` varchar(255),
	`cases_before_count` int DEFAULT 0,
	`avg_resolution_time_before` int,
	`climate_score_before` decimal(3,2),
	`satisfaction_score_before` decimal(3,2),
	`cases_after_count` int DEFAULT 0,
	`avg_resolution_time_after` int,
	`climate_score_after` decimal(3,2),
	`satisfaction_score_after` decimal(3,2),
	`measurement_period_months` int DEFAULT 3,
	`case_reduction_percentage` decimal(5,2),
	`resolution_time_improvement` decimal(5,2),
	`climate_score_improvement` decimal(5,2),
	`satisfaction_score_improvement` decimal(5,2),
	`effectiveness_score` decimal(5,2),
	`ai_insights` json,
	`status` enum('active','completed','archived') DEFAULT 'active',
	`created_by` int NOT NULL,
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `intervention_impact_analysis_id` PRIMARY KEY(`id`)
);
