CREATE TABLE `prediction_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`department_id` int NOT NULL,
	`department_name` varchar(255) NOT NULL,
	`predicted_risk_score` int NOT NULL,
	`predicted_turnover_rate` decimal(5,2),
	`actual_turnover_rate` decimal(5,2),
	`actual_terminations` int,
	`current_employee_count` int NOT NULL,
	`avg_tenure_months` decimal(10,2),
	`has_manager` boolean NOT NULL,
	`algorithm_config_id` int,
	`rotation_weight` int NOT NULL,
	`tenure_weight` int NOT NULL,
	`manager_weight` int NOT NULL,
	`team_size_weight` int NOT NULL,
	`accuracy_score` decimal(5,2),
	`prediction_error` decimal(5,2),
	`prediction_date` timestamp NOT NULL,
	`evaluation_date` timestamp,
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()),
	`status` varchar(50) DEFAULT 'pending',
	CONSTRAINT `prediction_history_id` PRIMARY KEY(`id`)
);
