CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`whatsapp_event_id` int,
	`nombre` varchar(255) NOT NULL,
	`email` varchar(255),
	`empresa` varchar(255),
	`telefono` varchar(50),
	`normativas` json,
	`estado` varchar(50) NOT NULL DEFAULT 'nuevo',
	`fecha_contacto` timestamp,
	`proxima_accion` timestamp,
	`proxima_accion_descripcion` text,
	`notas` text,
	`asignado_a` int,
	`asignado_nombre` varchar(255),
	`origen` varchar(100),
	`valor_estimado` decimal(10,2),
	`probabilidad_cierre` int DEFAULT 0,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()),
	`fecha_cierre` timestamp,
	`razon_perdida` text,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
