CREATE TABLE `threshold_experiments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`description` text,
	`config_id_a` int NOT NULL,
	`config_id_b` int NOT NULL,
	`start_date` timestamp NOT NULL,
	`end_date` timestamp,
	`precision_a` decimal(5,2),
	`recall_a` decimal(5,2),
	`f1_score_a` decimal(5,2),
	`accuracy_a` decimal(5,2),
	`precision_b` decimal(5,2),
	`recall_b` decimal(5,2),
	`f1_score_b` decimal(5,2),
	`accuracy_b` decimal(5,2),
	`winner_config_id` int,
	`conclusion` text,
	`status` varchar(20) NOT NULL DEFAULT 'active',
	`created_by` int NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `threshold_experiments_id` PRIMARY KEY(`id`)
);
