CREATE TABLE `retention_interventions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employee_id` int NOT NULL,
	`employee_name` varchar(255) NOT NULL,
	`employee_position` varchar(255),
	`department` varchar(255),
	`intervention_type` varchar(100) NOT NULL,
	`intervention_description` text NOT NULL,
	`cost` decimal(10,2),
	`implementation_date` date NOT NULL,
	`follow_up_date` date,
	`risk_score_before` decimal(5,2),
	`turnover_probability_before` decimal(5,2),
	`risk_score_after` decimal(5,2),
	`turnover_probability_after` decimal(5,2),
	`outcome` varchar(50),
	`outcome_date` date,
	`outcome_notes` text,
	`risk_reduction` decimal(5,2),
	`effectiveness_score` decimal(5,2),
	`created_by` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `retention_interventions_id` PRIMARY KEY(`id`)
);
