CREATE TABLE `budget_adjustment_scenarios` (
	`id` int AUTO_INCREMENT NOT NULL,
	`scenario_name` varchar(255) NOT NULL,
	`description` text,
	`created_by` int NOT NULL,
	`total_budget` decimal(12,2) NOT NULL,
	`budget_used` decimal(12,2) DEFAULT '0',
	`budget_remaining` decimal(12,2),
	`adjustments` json,
	`implementation_sequence` json,
	`total_employees_affected` int DEFAULT 0,
	`average_increase_percentage` decimal(5,2),
	`high_risk_employees_covered` int DEFAULT 0,
	`estimated_retention_rate` decimal(5,2),
	`estimated_turnover_cost_savings` decimal(12,2),
	`roi` decimal(5,2),
	`status` varchar(50) NOT NULL DEFAULT 'draft',
	`approved_by` int,
	`approved_at` timestamp,
	`implemented_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`last_updated` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `budget_adjustment_scenarios_id` PRIMARY KEY(`id`)
);
