CREATE TABLE `dc3_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`worker_name` varchar(255) NOT NULL,
	`worker_curp` varchar(18),
	`worker_occupation_cno_key` varchar(10),
	`worker_occupation_cno_desc` varchar(255),
	`worker_position` varchar(255),
	`company_name` varchar(255) NOT NULL,
	`company_rfc` varchar(15),
	`course_name` varchar(500) NOT NULL,
	`course_duration_hours` int,
	`period_start_date` date,
	`period_end_date` date,
	`thematic_area_key` varchar(10),
	`thematic_area_desc` varchar(255),
	`training_agent_name` varchar(255),
	`instructor_name` varchar(255),
	`employer_rep_name` varchar(255),
	`worker_rep_name` varchar(255),
	`status` enum('draft','issued','cancelled') NOT NULL DEFAULT 'draft',
	`folio_number` varchar(50),
	`notes` text,
	`created_by` int NOT NULL,
	`updated_by` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dc3_records_id` PRIMARY KEY(`id`)
);
