CREATE TABLE `dc3_client_companies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`razon_social` varchar(255) NOT NULL,
	`rfc` varchar(13) NOT NULL,
	`representante_legal` varchar(255),
	`domicilio` varchar(512),
	`municipio` varchar(100),
	`estado` varchar(100),
	`codigo_postal` varchar(5),
	`telefono` varchar(20),
	`email` varchar(255),
	`registro_patronal` varchar(20),
	`giro` varchar(255),
	`scian` varchar(10),
	`num_trabajadores` int,
	`logo_url` text,
	`logo_key` varchar(512),
	`is_active` boolean NOT NULL DEFAULT true,
	`is_default` boolean NOT NULL DEFAULT false,
	`notas` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dc3_client_companies_id` PRIMARY KEY(`id`)
);
