// NUEVA ESTRUCTURA OPTIMIZADA DEL SIDEBAR
// Reorganización lógica según secuencia del programa NOM-035

import { LayoutDashboard, Building2, Users, GraduationCap, ClipboardCheck, ShieldCheck, FileText, Scale, PieChart, Settings } from "lucide-react";

export const hierarchicalMenuItems = [
  {
    icon: LayoutDashboard,
    label: "Dashboard",
    path: "/",
    roles: ["admin", "instructor", "student", "committee"],
  },
  {
    icon: Building2,
    label: "Empresa",
    path: "/company",
    description: "Configuración general de la empresa",
    roles: ["admin"],
  },
  {
    icon: Users,
    label: "Gestión de Talento",
    description: "Administración de empleados y estructura organizacional",
    roles: ["admin"],
    submenu: [
      { label: "Trabajadores", path: "/employees", description: "Catálogo de trabajadores y expedientes digitales" },
      { label: "Departamentos", path: "/departments", description: "Catálogo de departamentos organizacionales" },
      { label: "Puestos", path: "/positions", description: "Catálogo de puestos y descripciones de trabajo" },
      { label: "Dashboard Organizacional", path: "/organization/dashboard", description: "Estadísticas visuales de empleados" },
      { label: "Organigrama", path: "/organization/chart", description: "Visualización de la estructura organizacional" },
      { label: "Cambios Organizacionales", path: "/organization/changes", description: "Historial de cambios organizacionales" },
      { label: "Dashboard de Rotación", path: "/employees/turnover", description: "Análisis de rotación de personal" },
      { label: "Importación Masiva", path: "/admin/import", description: "Importar datos desde Excel" },
    ],
  },
  {
    icon: GraduationCap,
    label: "Capacitación y Desarrollo",
    description: "Gestión de cursos, evaluaciones y certificaciones",
    roles: ["admin", "instructor", "student"],
    submenu: [
      { label: "Cursos", path: "/courses", description: "Catálogo de cursos y programas de capacitación" },
      { label: "Recursos", path: "/resources", description: "Material didáctico y recursos de capacitación" },
      { label: "Evaluaciones y Exámenes", path: "/assessments", description: "Gestión de evaluaciones en línea con banco de preguntas" },
      { label: "Banco de Preguntas", path: "/question-bank", description: "Administración del banco de preguntas para exámenes" },
      { label: "Certificados de Capacitación", path: "/training-certificates", description: "Generación de certificados oficiales STPS y RED CONOCER" },
      { label: "Certificados e.firma SAT", path: "/efirma-sat", description: "Gestión de certificados digitales del SAT" },
      { label: "Dashboard de Capacitación", path: "/training-dashboard", description: "Estadísticas y métricas de capacitación" },
      { label: "Notificaciones Automáticas", path: "/notifications-dashboard", description: "Gestión de plantillas y envío automático" },
      { label: "Competencias", path: "/competencies-dashboard", description: "Dashboard de competencias por trabajador" },
      { label: "Matriz de Habilidades", path: "/skills-matrix", description: "Matriz de habilidades del personal" },
      { label: "Evaluación de Competencias", path: "/competency-evaluation", description: "Evaluación de competencias y desempeño" },
      { label: "DNC Consolidada", path: "/dnc-dashboard", description: "Detección de Necesidades de Capacitación" },
      { label: "Catálogo de Competencias", path: "/competencies-manager", description: "Administración del catálogo de competencias" },
    ],
  },
  {
    icon: ClipboardCheck,
    label: "Encuestas NOM-035",
    description: "Cuestionarios de identificación y análisis de riesgos psicosociales",
    roles: ["admin", "committee"],
    submenu: [
      { label: "Cuestionario Interactivo (72 preguntas)", path: "/nom035/questionnaire", description: "Cuestionario completo NOM-035" },
      { label: "Guía I - ATS", path: "/surveys/guide-i", description: "Acontecimientos traumáticos severos" },
      { label: "Guía II - Identificación", path: "/surveys/guide-ii", description: "Identificación de factores de riesgo (16-50 trabajadores)" },
      { label: "Guía III - Evaluación", path: "/surveys/guide-iii", description: "Evaluación del entorno organizacional (50+ trabajadores)" },
      { label: "Tamaño de Muestra", path: "/surveys/sample-size", description: "Cálculo del tamaño de muestra" },
      { label: "Dashboard Tokens", path: "/surveys/tokens-dashboard", description: "Gestión de tokens de acceso" },
      { label: "Periodos de Aplicación", path: "/surveys/periods", description: "Configuración de periodos de aplicación" },
      { label: "Envío Masivo", path: "/surveys/mass-email", description: "Envío masivo de invitaciones" },
      { label: "Panel de Administración", path: "/surveys/nom035-admin", description: "Panel administrativo de encuestas" },
    ],
  },
  {
    icon: ShieldCheck,
    label: "Prevención de Riesgos Psicosociales",
    description: "Identificación, análisis y prevención de factores de riesgo",
    roles: ["admin", "committee"],
    submenu: [
      { label: "Gestión de Casos", path: "/cases", description: "Seguimiento de casos de riesgo psicosocial" },
      { label: "Investigación", path: "/cases/investigations", description: "Cuestionarios de mobbing y burnout" },
      { label: "Protocolo de Violencia Laboral", path: "/cases/workplace-violence", description: "Gestión de casos de violencia laboral" },
      { label: "Buzón de Quejas", path: "/mailbox", description: "Buzón de quejas y denuncias anónimas" },
      { label: "Análisis de Riesgos", path: "/risk-analysis", description: "Reportes de análisis de riesgos psicosociales" },
      { label: "Acciones Correctivas", path: "/surveys/corrective-actions", description: "Plan de acciones para mitigar riesgos" },
      { label: "Alertas Tempranas", path: "/alerts", description: "Dashboard de alertas críticas" },
      { 
        label: "Sistema de Alertas", 
        description: "Gestión y análisis de alertas",
        submenu: [
          { label: "Histórico de Alertas", path: "/alert-history", description: "Registro completo de alertas" },
          { label: "Dashboard de Métricas", path: "/alert-metrics", description: "Análisis avanzado con gráficas" },
          { label: "Historial de Notificaciones", path: "/notification-history", description: "Registro de notificaciones push" },
          { label: "Configuración de Umbrales", path: "/alert-thresholds", description: "Configurar umbrales de alertas" },
          { label: "Configuración de Reportes", path: "/alert-reports-config", description: "Frecuencia de reportes automáticos" },
        ]
      },
    ],
  },
  {
    icon: FileText,
    label: "Cumplimiento Normativo",
    description: "Verificación de cumplimiento NOM-035 y documentación",
    roles: ["admin", "committee"],
    submenu: [
      { 
        label: "Comité de Seguridad", 
        description: "Gestión del comité de seguridad y salud",
        submenu: [
          { label: "Miembros del Comité", path: "/committee", description: "Gestión de miembros del comité" },
          { label: "Programa de Capacitación", path: "/committee/training", description: "Programas de capacitación del comité" },
          { label: "Acta Constitutiva", path: "/committee/constitutive-act", description: "Documento de constitución del comité" },
          { label: "Bases de Funcionamiento", path: "/committee/operating-rules", description: "Reglamento interno del comité" },
          { label: "Aceptación de Cargo", path: "/committee/position-acceptance", description: "Documento de aceptación de cargo" },
          { label: "Gestión de Minutas", path: "/committee-minutes-management", description: "CRUD completo de minutas de comité" },
          { label: "Seguimiento de Acuerdos", path: "/agreements-dashboard", description: "Dashboard de seguimiento de acuerdos" },
          { label: "Minutas de Reunión", path: "/meeting-minutes", description: "Registro de minutas de reuniones" },
        ]
      },
      { label: "Cumplimiento NOM-035", path: "/compliance", description: "Checklist de cumplimiento normativo" },
      { label: "Verificación Numerales 7 y 8", path: "/compliance/numerals", description: "Verificación automática de obligaciones" },
      { label: "Historial de Reportes", path: "/compliance/reports-history", description: "Consulta y re-descarga de reportes" },
      { label: "Políticas", path: "/nom035/policies", description: "Políticas de prevención de riesgos" },
      { label: "Carpeta de Evidencias", path: "/nom035/evidences", description: "Repositorio de documentación" },
      { label: "Informe Numeral 7.5", path: "/reports/regulatory", description: "Informe de identificación y análisis" },
    ],
  },
  {
    icon: Scale,
    label: "Igualdad Laboral y No Discriminación",
    description: "Cumplimiento NMX-025-SCFI-2015",
    roles: ["admin"],
    submenu: [
      { label: "Política de Igualdad", path: "/equality/policy", description: "Política institucional de igualdad laboral" },
      { label: "Indicadores de Brecha Salarial", path: "/equality/salary-gap", description: "Análisis de brecha salarial por género" },
      { label: "Acciones Afirmativas", path: "/equality/affirmative-actions", description: "Programas para promover la igualdad" },
      { label: "Quejas y Denuncias", path: "/equality/complaints", description: "Sistema de atención a quejas" },
      { label: "Comité de Igualdad", path: "/equality/committee", description: "Comité responsable de la política" },
    ],
  },
  {
    icon: PieChart,
    label: "Reportes y Análisis",
    description: "Dashboards, reportes normativos y exportaciones",
    roles: ["admin", "instructor"],
    submenu: [
      { label: "Gráficas de Tendencias", path: "/trends", description: "Evolución temporal de casos y cumplimiento" },
      { label: "Reportes Normativos", path: "/reports/regulatory", description: "Reportes para cumplimiento NOM-035 y NMX-025" },
      { label: "Histórico de Alertas", path: "/alert-history", description: "Registro de alertas para auditoría" },
    ],
  },
  {
    icon: Settings,
    label: "Administración",
    description: "Configuración del sistema y gestión de usuarios",
    roles: ["admin"],
    submenu: [
      { label: "Usuarios", path: "/users", description: "Gestión de usuarios y permisos" },
      { label: "Configuración", path: "/settings", description: "Configuración general del sistema" },
      { label: "Catálogo de Formatos", path: "/document-formats", description: "Nomenclatura de folios para documentos" },
      { label: "Plantillas de Reportes", path: "/report-templates", description: "Plantillas personalizables HTML/CSS" },
      { label: "Auditoría de Documentos", path: "/document-audit", description: "Registro de accesos y descargas" },
      { label: "Alertas de Seguridad", path: "/security-alerts", description: "Monitoreo de actividad sospechosa" },
    ],
  },
];
